# Weather Temperature Analysis

We use weather temperatures from 1973-2021 from the DFW airport to find average maximum temperatures. We are also able to clean up the data set and remove null values in order to properly analyze the data.

Import NumPy to rad the data from the `data` variable

In [13]:
import numpy as np

Read data file. We need to skip the header using the `skip_header` parameter because that is not a part of the data and select the values we want to use using the `usecols()` parameter. 

In [6]:
import numpy as np

fp = '/Users/kayleechien/OneDrive - Greenhill School/DataScience/WeatherAnalysis/WeatherDataSet.txt'
data = np.genfromtxt(fp, skip_header=1, usecols=(0, 1, 2, 3))
print(data)

[[1973.    18.1   24.7   12.8]
 [1974.    18.6   25.5   13. ]
 [1975.    18.5   25.9   12. ]
 [1976.    17.8   25.6   11.1]
 [1977.    18.8   26.4   12. ]
 [1978.    17.8   25.4   11.1]
 [1979.    17.5   24.9   10.9]
 [1980.    19.1   27.    12.1]
 [1981.    18.4   25.8   11.7]
 [1982.    18.3   25.6   12.1]
 [1983.    17.3   24.2   11.1]
 [1984.    18.6   26.    12.6]
 [1985.    18.3   25.4   12.1]
 [1986.    18.8   25.8   12.9]
 [1987.    18.5   25.9   11.8]
 [1988.    18.7   26.4   12.1]
 [1989.    17.9   25.4   11.8]
 [1990.    19.3   26.6   12.5]
 [1991.    18.7   25.8   12.3]
 [1992.    18.7   25.6   12.5]
 [1993.    18.4   25.3   12.2]
 [1994.    18.9   25.8   12.5]
 [1995.    18.8   26.    12.2]
 [1996.    18.4   25.5   12.5]
 [1997.    18.    23.8   13.3]
 [1998.    20.3   26.1   15.5]
 [1999.    20.3   26.9   14.7]
 [2000.    19.7   26.4   13.7]
 [2001.    18.6   25.1   12.8]
 [2002.     nan    nan    nan]
 [2003.    18.9   26.1   12.7]
 [2004.    19.1   25.6   13.4]
 [2005. 

Use array splicing to only the dates into an array. Then we can try to get the average temperatures, maximum temperatures, and minimum temperatures using array splicing. Using `min()` and `max()` functions, we can get the minimum and maximum dates from the data. 

In [7]:
import numpy as np

fp = '/Users/kayleechien/OneDrive - Greenhill School/DataScience/WeatherAnalysis/WeatherDataSet.txt'
data = np.genfromtxt(fp, skip_header=1, usecols=(0, 1, 2, 3))
print(data)
date = data[:,0]
print(date)
temp_avg = data[:,1]
temp_max = data[:,2]
temp_min = data[:,3]


print(date.min())
print(date.max())

[[1973.    18.1   24.7   12.8]
 [1974.    18.6   25.5   13. ]
 [1975.    18.5   25.9   12. ]
 [1976.    17.8   25.6   11.1]
 [1977.    18.8   26.4   12. ]
 [1978.    17.8   25.4   11.1]
 [1979.    17.5   24.9   10.9]
 [1980.    19.1   27.    12.1]
 [1981.    18.4   25.8   11.7]
 [1982.    18.3   25.6   12.1]
 [1983.    17.3   24.2   11.1]
 [1984.    18.6   26.    12.6]
 [1985.    18.3   25.4   12.1]
 [1986.    18.8   25.8   12.9]
 [1987.    18.5   25.9   11.8]
 [1988.    18.7   26.4   12.1]
 [1989.    17.9   25.4   11.8]
 [1990.    19.3   26.6   12.5]
 [1991.    18.7   25.8   12.3]
 [1992.    18.7   25.6   12.5]
 [1993.    18.4   25.3   12.2]
 [1994.    18.9   25.8   12.5]
 [1995.    18.8   26.    12.2]
 [1996.    18.4   25.5   12.5]
 [1997.    18.    23.8   13.3]
 [1998.    20.3   26.1   15.5]
 [1999.    20.3   26.9   14.7]
 [2000.    19.7   26.4   13.7]
 [2001.    18.6   25.1   12.8]
 [2002.     nan    nan    nan]
 [2003.    18.9   26.1   12.7]
 [2004.    19.1   25.6   13.4]
 [2005. 

In [9]:
#finding the number of days 
date_mask = np.isfinite(date)
print("Number of days:", np.count_nonzero(date_mask))

Number of days: 49


In [11]:
import numpy as np

fp = '/Users/kayleechien/OneDrive - Greenhill School/DataScience/WeatherAnalysis/WeatherDataSet.txt'
data = np.genfromtxt(fp, skip_header=1, usecols=(0, 1, 2, 3))
date = data[:,0]
temp_avg = data[:,1]
temp_max = data[:,2]
temp_min = data[:,3]
#finding the number of missing days in the data
missing_date_mask = ~np.isfinite(date)
print("Number of missing days:", np.count_nonzero(missing_date_mask))

Number of missing days: 0


In [14]:
#finding average temperature days
tavg_mask = np.isfinite(temp_avg)
print("Number of average temps:", np.count_nonzero(tavg_mask))

Number of average temps: 46


In [15]:
#checking for missing data
missing_tmax_mask = ~np.isfinite(temp_max)
print("Number of missing tmax values:", np.count_nonzero(missing_tmax_mask))

Number of missing tmax values: 3


In [17]:
#Make a mask array, then remove bad values using the mask.
tmax_mask = np.isfinite(temp_max)
tmax_clean = temp_max[tmax_mask]

In [18]:
#We can also remove the corresponding dates by using the same mask (tmax_mask) on our date array.
date_clean = date[tmax_mask]



In [19]:
#average annual temperature, use a range of dates to find the average maximum temperature for one year
tmax_total = tmax_clean[(date_clean >= 1973) & (date_clean <= 2021)]
print(tmax_total.mean())

26.041304347826085
